/**
 * Decides whether a user is currently entitled to Pro.
 *
 * The `is_pro` flag alone used to be the whole answer, which made the system
 * fail *open*: it was only ever set back to FALSE by the
 * `customer.subscription.deleted` webhook, so any event we never received —
 * Stripe outage, a deploy window, a bug in the handler — left a cancelled
 * subscriber with Pro permanently. There was no second line of defence.
 *
 * `pro_expires_at` is that second line. Every subscription event writes the
 * current billing period's end into it, so access lapses on its own unless
 * something actively renews it. Losing a webhook now costs at most the rest
 * of a period the user already paid for, instead of costing the subscription
 * forever.
 *
 * One-time "lifetime" purchases genuinely never expire, so they are stored
 * with a NULL expiry and checked by plan name rather than by date.
 */

type EntitlementRow = {
  is_pro?: boolean | null;
  plan?: string | null;
  pro_expires_at?: Date | string | null;
};

/** Plans that are bought once and never renew, so they carry no expiry. */
const PERPETUAL_PLANS = new Set(["lifetime"]);

function isEntitled(row: EntitlementRow | null | undefined, now: Date = new Date()): boolean {
  if (!row || !row.is_pro) return false;
  if (row.plan && PERPETUAL_PLANS.has(row.plan)) return true;

  // A subscriber with no recorded expiry predates this column. Grandfathering
  // them in is deliberate: they paid, and the next subscription event Stripe
  // sends for them backfills a real date. Denying access on a missing value
  // would lock out every existing customer the moment this deploys.
  if (row.pro_expires_at == null) return true;

  const expiresAt = row.pro_expires_at instanceof Date ? row.pro_expires_at : new Date(row.pro_expires_at);
  if (Number.isNaN(expiresAt.getTime())) return true;

  return expiresAt.getTime() > now.getTime();
}

/**
 * Stripe moved `current_period_end` from the subscription onto its individual
 * items in the 2025-03-31.basil API version, which is the version this
 * account is pinned to. Both locations are read so the value keeps resolving
 * whether an event was generated by the new API or replayed from an older
 * one, and so a future SDK upgrade can't silently start returning `null`
 * here — which would hand out a perpetual entitlement without failing loudly.
 */
function periodEndFromSubscription(subscription: any): Date | null {
  const fromItem = subscription?.items?.data?.[0]?.current_period_end;
  const fromSubscription = subscription?.current_period_end;
  const seconds = typeof fromItem === "number" ? fromItem : fromSubscription;
  if (typeof seconds !== "number" || !Number.isFinite(seconds)) return null;
  return new Date(seconds * 1000);
}

export { isEntitled, periodEndFromSubscription, PERPETUAL_PLANS };
