import type { Lang } from "../i18n";

const en = {
  ecoTitle: "Background app efficiency rules",
  ecoDescription:
    "Choose non-critical apps for lower energy priority while PC Tweaker is open. Rules pause when an app becomes interactive; this is not a CPU percentage cap.",
  ecoAdd: "Choose executable",
  ecoEmpty: "No app rules yet.",
  ecoOn: "Rules enabled",
  ecoOff: "Rules paused",
  ecoRunning: "Engine running",
  ecoStopped: "Engine stopped",
  ecoActive: "Processes currently managed",
  ecoPending: "Restores pending",
  ecoConflict:
    "Windows power throttling is disabled globally. Restore that setting before using these rules.",
  doTitle: "Windows background download limit",
  doDescription:
    "Limit Delivery Optimization downloads from Microsoft. Administrator rights are required. Steam, other devices and your router are unaffected. This does not guarantee lower ping.",
  doValue: "Limit (KB/s)",
  doSave: "Set limit",
  doRestore: "Restore previous setting",
  doProvider: "Source",
  doConfigured: "Configured limit",
  doUnlimited: "No app limit configured",
  doReadback: "Configuration read back; actual download speed has not been measured.",
  doUnsupported: "Delivery Optimization control is unavailable on this Windows setup.",
  monitorTitle: "Game monitor refresh profile",
  monitorDescription:
    "Choose a supported refresh rate for one display during a game session. A preview reverts after 15 seconds unless confirmed; this does not increase GPU frame output.",
  monitorGuide: "Preview and confirm a different rate before saving a game rule.",
  monitorDisplay: "Display",
  monitorFrequency: "Refresh rate",
  monitorPreview: "Preview for 15 seconds",
  monitorConfirm: "Keep this refresh rate",
  monitorRestore: "Restore previous rate",
  monitorAdd: "Save game rule",
  monitorGame: "Choose game executable",
  monitorEmpty: "No game rules yet.",
  monitorNoDisplays: "No supported local display modes are available.",
  monitorRules: "Game rules",
  monitorPending: "Preview awaiting confirmation",
  enabled: "Enabled",
  disabled: "Paused",
  remove: "Remove",
  pro: "Pro",
  refresh: "Refresh state",
  working: "Working…",
  path: "Executable",
};

export type AdvancedCopy = typeof en;
export const ADVANCED_COPY: Record<Lang, AdvancedCopy> = {
  en,
  it: {
    ecoTitle: "Regole di efficienza per le app in background",
    ecoDescription:
      "Scegli app non critiche a priorità energetica ridotta mentre PC Tweaker è aperto. Le regole si sospendono quando l'app è interattiva; non sono un limite percentuale della CPU.",
    ecoAdd: "Scegli eseguibile",
    ecoEmpty: "Nessuna regola per le app.",
    ecoOn: "Regole attive",
    ecoOff: "Regole in pausa",
    ecoRunning: "Motore in esecuzione",
    ecoStopped: "Motore fermo",
    ecoActive: "Processi gestiti ora",
    ecoPending: "Ripristini in attesa",
    ecoConflict:
      "Il risparmio energetico di Windows è disattivato globalmente. Ripristina quell'impostazione prima di usare le regole.",
    doTitle: "Limite ai download Windows in background",
    doDescription:
      "Limita i download Microsoft gestiti da Delivery Optimization. Richiede privilegi di amministratore. Steam, altri dispositivi e router restano invariati. Non garantisce un ping inferiore.",
    doValue: "Limite (KB/s)",
    doSave: "Imposta limite",
    doRestore: "Ripristina impostazione precedente",
    doProvider: "Origine",
    doConfigured: "Limite configurato",
    doUnlimited: "Nessun limite impostato dall'app",
    doReadback: "Configurazione riletta; la velocità effettiva non è stata misurata.",
    doUnsupported: "Il controllo Delivery Optimization non è disponibile su questo Windows.",
    monitorTitle: "Profilo frequenza monitor per gioco",
    monitorDescription:
      "Scegli una frequenza supportata per un monitor durante la sessione di gioco. L'anteprima torna indietro dopo 15 secondi senza conferma; non aumenta i frame prodotti dalla GPU.",
    monitorGuide: "Prova e conferma una frequenza diversa prima di salvare una regola gioco.",
    monitorDisplay: "Monitor",
    monitorFrequency: "Frequenza",
    monitorPreview: "Anteprima per 15 secondi",
    monitorConfirm: "Mantieni questa frequenza",
    monitorRestore: "Ripristina frequenza precedente",
    monitorAdd: "Salva regola gioco",
    monitorGame: "Scegli eseguibile del gioco",
    monitorEmpty: "Nessuna regola gioco.",
    monitorNoDisplays: "Nessuna modalità monitor locale supportata.",
    monitorRules: "Regole gioco",
    monitorPending: "Anteprima in attesa di conferma",
    enabled: "Attivo",
    disabled: "In pausa",
    remove: "Rimuovi",
    pro: "Pro",
    refresh: "Aggiorna stato",
    working: "Operazione in corso…",
    path: "Eseguibile",
  },
  fr: {
    ecoTitle: "Règles d'efficacité des applications en arrière-plan",
    ecoDescription:
      "Choisissez des applications non critiques à priorité énergétique réduite tant que PC Tweaker est ouvert. Les règles se suspendent lorsque l'application devient interactive ; ce n'est pas un plafond CPU.",
    ecoAdd: "Choisir un exécutable",
    ecoEmpty: "Aucune règle d'application.",
    ecoOn: "Règles actives",
    ecoOff: "Règles en pause",
    ecoRunning: "Moteur en cours",
    ecoStopped: "Moteur arrêté",
    ecoActive: "Processus gérés actuellement",
    ecoPending: "Restaurations en attente",
    ecoConflict:
      "La limitation énergétique Windows est désactivée globalement. Restaurez ce réglage avant d'utiliser ces règles.",
    doTitle: "Limite des téléchargements Windows en arrière-plan",
    doDescription:
      "Limitez les téléchargements Microsoft gérés par Delivery Optimization. Des droits d'administrateur sont requis. Steam, les autres appareils et le routeur ne changent pas. Un ping inférieur n'est pas garanti.",
    doValue: "Limite (Ko/s)",
    doSave: "Définir la limite",
    doRestore: "Restaurer le réglage précédent",
    doProvider: "Source",
    doConfigured: "Limite configurée",
    doUnlimited: "Aucune limite définie par l'application",
    doReadback: "Configuration relue ; le débit réel n'a pas été mesuré.",
    doUnsupported: "Le contrôle Delivery Optimization est indisponible sur ce Windows.",
    monitorTitle: "Profil de fréquence du moniteur pour les jeux",
    monitorDescription:
      "Choisissez une fréquence prise en charge pour un écran pendant une session de jeu. L'aperçu revient en arrière après 15 secondes sans confirmation ; il n'augmente pas les images produites par le GPU.",
    monitorGuide:
      "Prévisualisez et confirmez une autre fréquence avant d'enregistrer une règle de jeu.",
    monitorDisplay: "Écran",
    monitorFrequency: "Fréquence",
    monitorPreview: "Aperçu pendant 15 secondes",
    monitorConfirm: "Conserver cette fréquence",
    monitorRestore: "Restaurer la fréquence précédente",
    monitorAdd: "Enregistrer la règle",
    monitorGame: "Choisir l'exécutable du jeu",
    monitorEmpty: "Aucune règle de jeu.",
    monitorNoDisplays: "Aucun mode d'écran local pris en charge.",
    monitorRules: "Règles de jeu",
    monitorPending: "Aperçu en attente de confirmation",
    enabled: "Actif",
    disabled: "En pause",
    remove: "Supprimer",
    pro: "Pro",
    refresh: "Actualiser l'état",
    working: "Opération en cours…",
    path: "Exécutable",
  },
  es: {
    ecoTitle: "Reglas de eficiencia para apps en segundo plano",
    ecoDescription:
      "Elige apps no críticas con menor prioridad energética mientras PC Tweaker está abierto. Las reglas se pausan cuando la app pasa a ser interactiva; no son un límite porcentual de CPU.",
    ecoAdd: "Elegir ejecutable",
    ecoEmpty: "Aún no hay reglas de apps.",
    ecoOn: "Reglas activas",
    ecoOff: "Reglas pausadas",
    ecoRunning: "Motor en marcha",
    ecoStopped: "Motor detenido",
    ecoActive: "Procesos gestionados ahora",
    ecoPending: "Restauraciones pendientes",
    ecoConflict:
      "El ahorro energético de Windows está desactivado globalmente. Restaura ese ajuste antes de usar estas reglas.",
    doTitle: "Límite de descargas de Windows en segundo plano",
    doDescription:
      "Limita las descargas de Microsoft gestionadas por Delivery Optimization. Requiere permisos de administrador. Steam, otros dispositivos y el router no cambian. No garantiza menos ping.",
    doValue: "Límite (KB/s)",
    doSave: "Fijar límite",
    doRestore: "Restaurar ajuste anterior",
    doProvider: "Origen",
    doConfigured: "Límite configurado",
    doUnlimited: "La app no ha configurado ningún límite",
    doReadback: "Configuración leída; no se ha medido la velocidad real.",
    doUnsupported: "El control de Delivery Optimization no está disponible en este Windows.",
    monitorTitle: "Perfil de frecuencia del monitor para juegos",
    monitorDescription:
      "Elige una frecuencia compatible para una pantalla durante la sesión de juego. La vista previa se revierte a los 15 segundos si no se confirma; no aumenta los fotogramas que genera la GPU.",
    monitorGuide: "Previsualiza y confirma otra frecuencia antes de guardar una regla de juego.",
    monitorDisplay: "Pantalla",
    monitorFrequency: "Frecuencia",
    monitorPreview: "Vista previa de 15 segundos",
    monitorConfirm: "Mantener esta frecuencia",
    monitorRestore: "Restaurar frecuencia anterior",
    monitorAdd: "Guardar regla del juego",
    monitorGame: "Elegir ejecutable del juego",
    monitorEmpty: "Aún no hay reglas de juegos.",
    monitorNoDisplays: "No hay modos de pantalla local compatibles.",
    monitorRules: "Reglas de juegos",
    monitorPending: "Vista previa pendiente de confirmación",
    enabled: "Activado",
    disabled: "Pausado",
    remove: "Quitar",
    pro: "Pro",
    refresh: "Actualizar estado",
    working: "Trabajando…",
    path: "Ejecutable",
  },
  de: {
    ecoTitle: "Effizienzregeln für Hintergrund-Apps",
    ecoDescription:
      "Wählen Sie unkritische Apps für eine niedrigere Energiepriorität, solange PC Tweaker geöffnet ist. Bei interaktiver Nutzung pausieren die Regeln; sie sind keine CPU-Prozentgrenze.",
    ecoAdd: "Programmdatei wählen",
    ecoEmpty: "Noch keine App-Regeln.",
    ecoOn: "Regeln aktiv",
    ecoOff: "Regeln pausiert",
    ecoRunning: "Steuerung läuft",
    ecoStopped: "Steuerung gestoppt",
    ecoActive: "Aktuell verwaltete Prozesse",
    ecoPending: "Ausstehende Wiederherstellungen",
    ecoConflict:
      "Windows-Energiedrosselung ist global deaktiviert. Stellen Sie diese Einstellung vor der Nutzung der Regeln wieder her.",
    doTitle: "Limit für Windows-Hintergrunddownloads",
    doDescription:
      "Begrenzt Microsoft-Downloads über Delivery Optimization. Administratorrechte sind erforderlich. Steam, andere Geräte und der Router bleiben unverändert. Ein niedrigerer Ping ist nicht garantiert.",
    doValue: "Limit (KB/s)",
    doSave: "Limit setzen",
    doRestore: "Vorherige Einstellung wiederherstellen",
    doProvider: "Quelle",
    doConfigured: "Konfiguriertes Limit",
    doUnlimited: "Kein App-Limit konfiguriert",
    doReadback: "Konfiguration gelesen; die tatsächliche Downloadrate wurde nicht gemessen.",
    doUnsupported: "Delivery Optimization kann auf diesem Windows nicht gesteuert werden.",
    monitorTitle: "Monitorfrequenzprofil für Spiele",
    monitorDescription:
      "Wählen Sie eine unterstützte Frequenz für einen Monitor während einer Spielesitzung. Ohne Bestätigung wird die Vorschau nach 15 Sekunden zurückgesetzt; die GPU erzeugt dadurch nicht mehr Bilder.",
    monitorGuide:
      "Andere Frequenzen vor dem Speichern einer Spielregel als Vorschau testen und bestätigen.",
    monitorDisplay: "Monitor",
    monitorFrequency: "Bildwiederholrate",
    monitorPreview: "15 Sekunden Vorschau",
    monitorConfirm: "Frequenz beibehalten",
    monitorRestore: "Vorherige Frequenz wiederherstellen",
    monitorAdd: "Spielregel speichern",
    monitorGame: "Programmdatei des Spiels wählen",
    monitorEmpty: "Noch keine Spielregeln.",
    monitorNoDisplays: "Keine unterstützten lokalen Monitormodi verfügbar.",
    monitorRules: "Spielregeln",
    monitorPending: "Vorschau wartet auf Bestätigung",
    enabled: "Aktiv",
    disabled: "Pausiert",
    remove: "Entfernen",
    pro: "Pro",
    refresh: "Status aktualisieren",
    working: "Wird ausgeführt…",
    path: "Programmdatei",
  },
  pt: {
    ecoTitle: "Regras de eficiência para apps em segundo plano",
    ecoDescription:
      "Escolha apps não críticas com menor prioridade energética enquanto o PC Tweaker está aberto. As regras pausam quando a app fica interativa; não são um limite percentual da CPU.",
    ecoAdd: "Escolher executável",
    ecoEmpty: "Ainda não há regras de apps.",
    ecoOn: "Regras ativas",
    ecoOff: "Regras em pausa",
    ecoRunning: "Motor em execução",
    ecoStopped: "Motor parado",
    ecoActive: "Processos geridos agora",
    ecoPending: "Restauros pendentes",
    ecoConflict:
      "A limitação energética do Windows está desativada globalmente. Restaure essa definição antes de usar estas regras.",
    doTitle: "Limite de transferências Windows em segundo plano",
    doDescription:
      "Limita transferências Microsoft geridas por Delivery Optimization. Requer direitos de administrador. Steam, outros dispositivos e o router não mudam. Não garante menor latência.",
    doValue: "Limite (KB/s)",
    doSave: "Definir limite",
    doRestore: "Restaurar definição anterior",
    doProvider: "Origem",
    doConfigured: "Limite configurado",
    doUnlimited: "Nenhum limite definido pela app",
    doReadback: "Configuração confirmada; a velocidade real não foi medida.",
    doUnsupported: "O controlo Delivery Optimization não está disponível neste Windows.",
    monitorTitle: "Perfil de frequência do monitor para jogos",
    monitorDescription:
      "Escolha uma frequência suportada para um monitor durante uma sessão de jogo. A pré-visualização reverte após 15 segundos sem confirmação; não aumenta os fotogramas produzidos pela GPU.",
    monitorGuide: "Pré-visualize e confirme outra frequência antes de guardar uma regra de jogo.",
    monitorDisplay: "Monitor",
    monitorFrequency: "Frequência",
    monitorPreview: "Pré-visualizar por 15 segundos",
    monitorConfirm: "Manter esta frequência",
    monitorRestore: "Restaurar frequência anterior",
    monitorAdd: "Guardar regra de jogo",
    monitorGame: "Escolher executável do jogo",
    monitorEmpty: "Ainda não há regras de jogos.",
    monitorNoDisplays: "Não há modos de monitor local suportados.",
    monitorRules: "Regras de jogos",
    monitorPending: "Pré-visualização por confirmar",
    enabled: "Ativo",
    disabled: "Em pausa",
    remove: "Remover",
    pro: "Pro",
    refresh: "Atualizar estado",
    working: "Em curso…",
    path: "Executável",
  },
};
