import type { Lang } from "../i18n";

const en = {
  eyebrow: "SYSTEM CHECK",
  title: "Know what needs your attention.",
  intro:
    "Check this PC's settings, storage, startup, memory, security signals and driver dates. Review the evidence before making a change.",
  start: "Scan this PC",
  running: "Reading your system",
  presenting: "Preparing your results",
  discovering: "Discovering device categories",
  waitingWindows: "Waiting for the Windows inventory",
  deviceClasses: "device categories checked",
  elapsed: "Elapsed",
  scanning: "Scanning",
  finishing: "Finishing",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop",
  finish: "End scan",
  paused: "Paused",
  pausedLine: "Paused: {done} of {total} checks done",
  pausedHint: "Resume reads only what is still missing. Closing PC Tweaker discards a paused scan.",
  partialTitle: "Partial scan",
  partialBody: "{done} of {total} checks completed. Not checked: {missing}.",
  olderNote: "Some of these results were read at {time}, before the pause.",
  complete: "Scan complete",
  results: "Scan results",
  hideResults: "Hide results",
  showResults: "Show results",
  partial: "Some checks could not finish",
  scope: "What we check",
  newChecks: "3 new checks",
  newDetails: [
    "Third-party tasks that run at sign-in or boot.",
    "Installed optional apps; removal stays your choice.",
    "Detect conflicts that prevent your app rules from working.",
  ],
  sources: "completed checks",
  recommendations: "Recommended changes",
  optional: "Optional improvements",
  optionalBody:
    "These inactive settings depend on how you use your PC. Review their trade-offs individually; they are not faults and are not included in Fix all.",
  proRecommendations: "Recommendations available with Pro",
  proRecommendationsBody:
    "These settings match the hardware advice but require Pro. If you already subscribe, sign in to your account.",
  review: "Needs your review",
  empty: "No supported changes to apply.",
  emptyBody:
    "No unapplied hardware-recommended settings can be applied automatically by this account. Review the findings and optional settings listed separately.",
  ready: "A clear report. A choice for every change.",
  readyBody:
    "Scanning does not apply tweaks, delete files or install drivers. Results distinguish supported fixes from items that need your decision.",
  selected: "selected",
  apply: "Apply selected",
  confirm: "Review your changes",
  confirmBody:
    "Only the selected settings below will be changed. Files, startup apps, drivers and security settings are not changed by Fix all. Supported settings can be restored from Change history.",
  cancel: "Cancel",
  verified: "Verified as applied",
  failed: "Not applied or not verified",
  skipped: "No longer eligible",
  retry: "Scan again before retrying.",
  verifying: "Applying and verifying settings…",
  admin: "Administrator approval",
  noReview: "No review items found in the completed checks.",
  unavailable: "Unavailable checks remain unknown, not passed.",
  manual: "Review",
  probes: [
    "Windows settings",
    "Supported changes",
    "Hardware recommendations",
    "System profile",
    "Free storage",
    "Startup programs",
    "Memory usage",
    "Pending restart",
    "Security signals",
    "Driver dates",
    "Scheduled startup tasks",
    "Optional Windows apps",
    "Background efficiency",
  ],
  observations: {
    tasks: [
      "Review scheduled startup tasks",
      "These enabled third-party tasks run at sign-in or boot. Review their purpose before disabling them.",
    ],
    apps: [
      "Review optional Windows apps",
      "These apps are installed and removable for this account. Keep what you use; removal may erase local app data.",
    ],
    efficiency: [
      "Background rules cannot take effect",
      "Global power throttling is disabled. Review the conflicting setting in Performance before using efficiency rules.",
    ],
    storage: [
      "Low free storage",
      "Less than 15% is free. Review files and cleanup options before deleting anything. The figures below show free space.",
    ],
    startup: [
      "Review programs that start with Windows",
      "These entries are enabled. Keep the ones you rely on; their presence alone does not mean startup is slow.",
    ],
    memory: [
      "High memory usage at scan time",
      "Review your workload first. A single reading does not prove a memory problem; cleanup can temporarily slow apps down.",
    ],
    restart: [
      "Windows reports a pending restart",
      "Save your work and restart when convenient. PC Tweaker will not restart the computer for you.",
    ],
    security: [
      "A Windows protection appears disabled",
      "Inspect the protection in Windows Security or UAC settings. Managed devices and third-party security software may need a different configuration.",
    ],
    drivers: [
      "Review this driver's date",
      "The reported date is at least two years old. Age alone does not prove a driver is outdated or that a compatible update exists.",
    ],
  },
};
type Copy = typeof en;
export const SCAN_COPY: Record<Lang, Copy> = {
  en,
  it: {
    ...en,
    eyebrow: "CONTROLLO SISTEMA",
    title: "Scopri cosa richiede attenzione.",
    intro:
      "Controlla impostazioni, spazio, avvio, memoria, segnali di sicurezza e date dei driver. Esamina i dati prima di intervenire.",
    start: "Analizza questo PC",
    running: "Lettura del sistema",
    presenting: "Preparazione dei risultati",
    discovering: "Ricerca delle categorie di dispositivi",
    waitingWindows: "Attesa dell'inventario Windows",
    deviceClasses: "categorie di dispositivi controllate",
    elapsed: "Tempo trascorso",
    scanning: "Scansione",
    finishing: "Completamento",
    pause: "Pausa",
    resume: "Riprendi",
    stop: "Ferma",
    finish: "Termina",
    paused: "In pausa",
    pausedLine: "In pausa: {done} di {total} controlli completati",
    pausedHint:
      "Riprendi legge solo ciò che manca. Chiudendo PC Tweaker la scansione in pausa viene scartata.",
    partialTitle: "Scansione parziale",
    partialBody: "{done} di {total} controlli completati. Non controllati: {missing}.",
    olderNote: "Alcuni di questi risultati sono stati letti alle {time}, prima della pausa.",
    complete: "Analisi completata",
    results: "Risultati dell’analisi",
    hideResults: "Nascondi risultati",
    showResults: "Mostra risultati",
    partial: "Alcuni controlli non sono riusciti",
    scope: "Cosa controlliamo",
    newChecks: "3 nuovi controlli",
    newDetails: [
      "Attività di terze parti avviate all’accesso o all’accensione.",
      "App facoltative installate; scegli tu se rimuoverle.",
      "Rileva i conflitti che impediscono alle regole di funzionare.",
    ],
    sources: "controlli completati",
    recommendations: "Modifiche consigliate",
    optional: "Miglioramenti facoltativi",
    optionalBody:
      "Queste impostazioni inattive dipendono da come usi il PC. Valutane gli effetti singolarmente: non sono errori e non rientrano in Correggi tutto.",
    proRecommendations: "Consigli disponibili con Pro",
    proRecommendationsBody:
      "Queste impostazioni corrispondono ai consigli hardware ma richiedono Pro. Se sei già abbonato, accedi al tuo account.",
    review: "Da esaminare",
    empty: "Nessuna modifica supportata da applicare.",
    emptyBody:
      "Nessuna impostazione consigliata per l'hardware e ancora inattiva è applicabile automaticamente da questo account. Esamina i risultati e le opzioni elencati separatamente.",
    ready: "Un report chiaro. Ogni scelta è tua.",
    readyBody:
      "L'analisi non applica tweak, elimina file o installa driver. Distingue le correzioni supportate dagli elementi che richiedono una tua decisione.",
    selected: "selezionati",
    apply: "Applica selezionati",
    confirm: "Esamina le modifiche",
    confirmBody:
      "Verranno cambiate solo le impostazioni selezionate. Correggi tutto non modifica file, programmi di avvio, driver o protezioni. Puoi ripristinare le impostazioni supportate dalla cronologia.",
    cancel: "Annulla",
    verified: "Applicazione verificata",
    failed: "Non applicati o non verificati",
    skipped: "Non più idonei",
    retry: "Ripeti l'analisi prima di riprovare.",
    verifying: "Applicazione e verifica…",
    admin: "Approvazione amministratore",
    noReview: "Nessun elemento da esaminare nei controlli completati.",
    unavailable: "I controlli non disponibili restano sconosciuti, non superati.",
    manual: "Esamina",
    probes: [
      "Impostazioni Windows",
      "Modifiche supportate",
      "Consigli per l'hardware",
      "Profilo del sistema",
      "Spazio libero",
      "Programmi di avvio",
      "Utilizzo memoria",
      "Riavvio pendente",
      "Segnali di sicurezza",
      "Date dei driver",
      "Attività pianificate all’avvio",
      "App Windows facoltative",
      "Efficienza in background",
    ],
    observations: {
      tasks: [
        "Esamina le attività pianificate all’avvio",
        "Queste attività di terze parti sono attive all’accesso o all’accensione. Valutane lo scopo prima di disattivarle.",
      ],
      apps: [
        "Esamina le app Windows facoltative",
        "Queste app sono installate e rimovibili per questo account. Conserva ciò che usi; la rimozione può cancellare dati locali.",
      ],
      efficiency: [
        "Le regole in background non possono agire",
        "Il power throttling globale è disabilitato. Esamina l’impostazione in conflitto in Performance prima di usare le regole di efficienza.",
      ],
      storage: [
        "Poco spazio libero",
        "Meno del 15% è libero. Esamina file e opzioni di pulizia prima di eliminare qualcosa. I dati indicano lo spazio libero.",
      ],
      startup: [
        "Esamina i programmi di avvio",
        "Questi elementi sono abilitati. Mantieni quelli utili: la loro presenza non indica necessariamente un avvio lento.",
      ],
      memory: [
        "Memoria molto utilizzata durante l'analisi",
        "Controlla prima i programmi aperti. Un solo dato non prova un problema; la pulizia può rallentare temporaneamente le app.",
      ],
      restart: [
        "Windows segnala un riavvio pendente",
        "Salva il lavoro e riavvia quando preferisci. PC Tweaker non riavvierà il computer.",
      ],
      security: [
        "Una protezione Windows sembra disattivata",
        "Controlla Sicurezza di Windows o le impostazioni UAC. PC aziendali e antivirus di terze parti possono richiedere configurazioni diverse.",
      ],
      drivers: [
        "Esamina la data di questo driver",
        "La data indicata risale ad almeno due anni fa. Non prova che il driver sia obsoleto o che esista un aggiornamento compatibile.",
      ],
    },
  },
  fr: {
    ...en,
    eyebrow: "CONTRÔLE DU SYSTÈME",
    title: "Identifiez ce qui mérite votre attention.",
    intro:
      "Vérifiez les réglages, le stockage, le démarrage, la mémoire, les protections et les dates des pilotes avant toute modification.",
    start: "Analyser ce PC",
    running: "Lecture du système",
    presenting: "Préparation des résultats",
    discovering: "Recherche des catégories de périphériques",
    waitingWindows: "En attente de l’inventaire Windows",
    deviceClasses: "catégories de périphériques vérifiées",
    elapsed: "Temps écoulé",
    scanning: "Analyse",
    finishing: "Finalisation",
    pause: "Pause",
    resume: "Reprendre",
    stop: "Arrêter",
    finish: "Terminer",
    paused: "En pause",
    pausedLine: "En pause : {done} contrôles sur {total} terminés",
    pausedHint:
      "Reprendre ne lit que ce qui manque encore. Fermer PC Tweaker abandonne une analyse en pause.",
    partialTitle: "Analyse partielle",
    partialBody: "{done} contrôles sur {total} terminés. Non vérifiés : {missing}.",
    olderNote: "Certains de ces résultats ont été lus à {time}, avant la pause.",
    complete: "Analyse terminée",
    results: "Résultats de l’analyse",
    hideResults: "Masquer les résultats",
    showResults: "Afficher les résultats",
    partial: "Certains contrôles ont échoué",
    scope: "Points contrôlés",
    newChecks: "3 nouveaux contrôles",
    newDetails: [
      "Tâches tierces lancées à la connexion ou au démarrage.",
      "Applications facultatives installées ; vous décidez des suppressions.",
      "Détecte les conflits qui empêchent vos règles de fonctionner.",
    ],
    sources: "contrôles terminés",
    recommendations: "Modifications recommandées",
    optional: "Améliorations facultatives",
    optionalBody:
      "Ces réglages inactifs dépendent de votre usage du PC. Examinez leurs effets individuellement : ce ne sont pas des erreurs et ils sont exclus de Tout corriger.",
    proRecommendations: "Recommandations disponibles avec Pro",
    proRecommendationsBody:
      "Ces réglages correspondent aux conseils matériels mais nécessitent Pro. Si vous êtes déjà abonné, connectez-vous à votre compte.",
    review: "À examiner",
    empty: "Aucune modification prise en charge à appliquer.",
    emptyBody:
      "Ce compte ne peut appliquer automatiquement aucun réglage matériel recommandé encore inactif. Consultez les résultats et les options présentés séparément.",
    ready: "Un rapport clair. Chaque décision vous appartient.",
    readyBody:
      "L'analyse ne modifie aucun réglage, ne supprime aucun fichier et n'installe aucun pilote. Les corrections sont séparées des points à examiner.",
    selected: "sélectionnés",
    apply: "Appliquer la sélection",
    confirm: "Examiner les modifications",
    confirmBody:
      "Seuls les réglages sélectionnés seront modifiés. Les fichiers, programmes de démarrage, pilotes et protections restent inchangés. Les réglages pris en charge peuvent être restaurés dans l'historique.",
    cancel: "Annuler",
    verified: "Application vérifiée",
    failed: "Non appliqués ou non vérifiés",
    skipped: "Ne sont plus admissibles",
    retry: "Relancez l'analyse avant de réessayer.",
    verifying: "Application et vérification…",
    admin: "Autorisation administrateur",
    noReview: "Aucun point à examiner parmi les contrôles terminés.",
    unavailable: "Un contrôle indisponible reste inconnu, pas réussi.",
    manual: "Examiner",
    probes: [
      "Réglages Windows",
      "Modifications prises en charge",
      "Conseils matériels",
      "Profil système",
      "Espace libre",
      "Programmes de démarrage",
      "Utilisation mémoire",
      "Redémarrage requis",
      "Protections",
      "Dates des pilotes",
      "Tâches planifiées au démarrage",
      "Applications Windows facultatives",
      "Efficacité en arrière-plan",
    ],
    observations: {
      tasks: [
        "Examiner les tâches de démarrage",
        "Ces tâches tierces sont activées à la connexion ou au démarrage. Vérifiez leur rôle avant de les désactiver.",
      ],
      apps: [
        "Examiner les applications facultatives",
        "Ces applications sont installées et peuvent être supprimées pour ce compte. Gardez celles que vous utilisez ; des données locales peuvent être perdues.",
      ],
      efficiency: [
        "Les règles ne peuvent pas agir",
        "La limitation énergétique globale est désactivée. Examinez le réglage en conflit dans Performance avant d’utiliser les règles.",
      ],
      storage: [
        "Peu d'espace libre",
        "Moins de 15 % d'espace libre. Examinez les fichiers avant toute suppression. Les chiffres indiquent l'espace libre.",
      ],
      startup: [
        "Examiner les programmes de démarrage",
        "Ces programmes sont activés. Gardez ceux qui vous sont utiles ; leur présence ne prouve pas un démarrage lent.",
      ],
      memory: [
        "Utilisation mémoire élevée lors de l'analyse",
        "Vérifiez les applications ouvertes. Une seule mesure ne prouve pas un problème ; le nettoyage peut ralentir temporairement les applications.",
      ],
      restart: [
        "Windows demande un redémarrage",
        "Enregistrez votre travail et redémarrez quand cela vous convient. PC Tweaker ne redémarre pas le PC.",
      ],
      security: [
        "Une protection Windows semble désactivée",
        "Vérifiez Sécurité Windows ou les réglages UAC. Les PC gérés et les antivirus tiers peuvent nécessiter une autre configuration.",
      ],
      drivers: [
        "Examiner la date de ce pilote",
        "La date indiquée remonte à au moins deux ans. Cela ne prouve pas que le pilote est obsolète ni qu'une mise à jour compatible existe.",
      ],
    },
  },
  es: {
    ...en,
    eyebrow: "REVISIÓN DEL SISTEMA",
    title: "Descubre qué necesita atención.",
    intro:
      "Revisa ajustes, almacenamiento, inicio, memoria, protecciones y fechas de controladores antes de hacer cambios.",
    start: "Analizar este PC",
    running: "Leyendo el sistema",
    presenting: "Preparando los resultados",
    discovering: "Buscando categorías de dispositivos",
    waitingWindows: "Esperando el inventario de Windows",
    deviceClasses: "categorías de dispositivos comprobadas",
    elapsed: "Tiempo transcurrido",
    scanning: "Analizando",
    finishing: "Finalizando",
    pause: "Pausar",
    resume: "Reanudar",
    stop: "Detener",
    finish: "Terminar",
    paused: "En pausa",
    pausedLine: "En pausa: {done} de {total} comprobaciones hechas",
    pausedHint:
      "Al reanudar solo se lee lo que falta. Si cierras PC Tweaker, el análisis en pausa se descarta.",
    partialTitle: "Análisis parcial",
    partialBody: "{done} de {total} comprobaciones completadas. Sin comprobar: {missing}.",
    olderNote: "Algunos de estos resultados se leyeron a las {time}, antes de la pausa.",
    complete: "Análisis completo",
    results: "Resultados del análisis",
    hideResults: "Ocultar resultados",
    showResults: "Mostrar resultados",
    partial: "Algunas comprobaciones no finalizaron",
    scope: "Qué comprobamos",
    newChecks: "3 comprobaciones nuevas",
    newDetails: [
      "Tareas de terceros que se ejecutan al iniciar sesión o arrancar.",
      "Aplicaciones opcionales instaladas; tú decides si eliminarlas.",
      "Detecta conflictos que impiden que tus reglas funcionen.",
    ],
    sources: "comprobaciones completas",
    recommendations: "Cambios recomendados",
    optional: "Mejoras opcionales",
    optionalBody:
      "Estos ajustes inactivos dependen de cómo utilizas el PC. Revisa sus efectos individualmente: no son errores ni se incluyen en Corregir todo.",
    proRecommendations: "Recomendaciones disponibles con Pro",
    proRecommendationsBody:
      "Estos ajustes coinciden con los consejos de hardware, pero requieren Pro. Si ya tienes una suscripción, inicia sesión en tu cuenta.",
    review: "Para revisar",
    empty: "No hay cambios compatibles que aplicar.",
    emptyBody:
      "Esta cuenta no puede aplicar automáticamente ningún ajuste recomendado para el hardware que siga inactivo. Revisa los resultados y las opciones por separado.",
    ready: "Un informe claro. Tú eliges cada cambio.",
    readyBody:
      "El análisis no aplica ajustes, elimina archivos ni instala controladores. Separa correcciones compatibles de elementos que requieren tu decisión.",
    selected: "seleccionados",
    apply: "Aplicar selección",
    confirm: "Revisar cambios",
    confirmBody:
      "Solo se cambiarán los ajustes seleccionados. No se modifican archivos, programas de inicio, controladores ni protecciones. Puedes restaurar los ajustes compatibles desde el historial.",
    cancel: "Cancelar",
    verified: "Aplicación verificada",
    failed: "No aplicados o no verificados",
    skipped: "Ya no cumplen los requisitos",
    retry: "Vuelve a analizar antes de reintentar.",
    verifying: "Aplicando y verificando…",
    admin: "Permiso de administrador",
    noReview: "No hay elementos para revisar en las comprobaciones completas.",
    unavailable: "Una comprobación no disponible es desconocida, no superada.",
    manual: "Revisar",
    probes: [
      "Ajustes de Windows",
      "Cambios compatibles",
      "Consejos para el hardware",
      "Perfil del sistema",
      "Espacio libre",
      "Programas de inicio",
      "Uso de memoria",
      "Reinicio pendiente",
      "Protecciones",
      "Fechas de controladores",
      "Tareas de inicio programadas",
      "Aplicaciones opcionales de Windows",
      "Eficiencia en segundo plano",
    ],
    observations: {
      tasks: [
        "Revisar las tareas de inicio",
        "Estas tareas de terceros están activas al iniciar sesión o arrancar. Revisa su función antes de desactivarlas.",
      ],
      apps: [
        "Revisar las aplicaciones opcionales",
        "Estas aplicaciones están instaladas y se pueden eliminar para esta cuenta. Conserva las que uses; podrías perder datos locales.",
      ],
      efficiency: [
        "Las reglas no pueden actuar",
        "La limitación energética global está desactivada. Revisa el ajuste en conflicto en Rendimiento antes de usar las reglas.",
      ],
      storage: [
        "Poco espacio libre",
        "Queda menos del 15 %. Revisa archivos y opciones de limpieza antes de borrar. Las cifras indican espacio libre.",
      ],
      startup: [
        "Revisa los programas de inicio",
        "Estos programas están habilitados. Conserva los que necesitas; su presencia no demuestra un inicio lento.",
      ],
      memory: [
        "Uso elevado de memoria durante el análisis",
        "Revisa primero las aplicaciones abiertas. Una sola lectura no demuestra un problema; limpiar puede ralentizar temporalmente las apps.",
      ],
      restart: [
        "Windows indica un reinicio pendiente",
        "Guarda tu trabajo y reinicia cuando te convenga. PC Tweaker no reiniciará el equipo.",
      ],
      security: [
        "Una protección de Windows parece desactivada",
        "Revisa Seguridad de Windows o UAC. Los equipos administrados y antivirus de terceros pueden requerir otra configuración.",
      ],
      drivers: [
        "Revisa la fecha de este controlador",
        "La fecha indicada tiene al menos dos años. Esto no demuestra que esté obsoleto ni que exista una actualización compatible.",
      ],
    },
  },
  de: {
    ...en,
    eyebrow: "SYSTEMPRÜFUNG",
    title: "Erkennen, wo Handlungsbedarf besteht.",
    intro:
      "Prüfe Einstellungen, Speicherplatz, Autostart, Arbeitsspeicher, Schutzfunktionen und Treiberdaten, bevor du etwas änderst.",
    start: "Diesen PC prüfen",
    running: "System wird geprüft",
    presenting: "Ergebnisse werden vorbereitet",
    discovering: "Gerätekategorien werden ermittelt",
    waitingWindows: "Windows-Inventar wird abgerufen",
    deviceClasses: "Gerätekategorien geprüft",
    elapsed: "Verstrichen",
    scanning: "Prüfung läuft",
    finishing: "Abschluss",
    pause: "Pausieren",
    resume: "Fortsetzen",
    stop: "Stoppen",
    finish: "Beenden",
    paused: "Pausiert",
    pausedLine: "Pausiert: {done} von {total} Prüfungen erledigt",
    pausedHint:
      "Beim Fortsetzen wird nur gelesen, was noch fehlt. Wenn du PC Tweaker schließt, wird eine pausierte Prüfung verworfen.",
    partialTitle: "Unvollständige Prüfung",
    partialBody: "{done} von {total} Prüfungen abgeschlossen. Nicht geprüft: {missing}.",
    olderNote: "Einige dieser Ergebnisse wurden um {time} gelesen, vor der Pause.",
    complete: "Prüfung abgeschlossen",
    results: "Prüfergebnisse",
    hideResults: "Ergebnisse ausblenden",
    showResults: "Ergebnisse anzeigen",
    partial: "Einige Prüfungen sind fehlgeschlagen",
    scope: "Prüfumfang",
    newChecks: "3 neue Prüfungen",
    newDetails: [
      "Drittanbieter-Aufgaben bei Anmeldung oder Systemstart.",
      "Installierte optionale Apps; du entscheidest über die Entfernung.",
      "Erkennt Konflikte, die deine App-Regeln blockieren.",
    ],
    sources: "abgeschlossene Prüfungen",
    recommendations: "Empfohlene Änderungen",
    optional: "Optionale Verbesserungen",
    optionalBody:
      "Diese inaktiven Einstellungen hängen von der PC-Nutzung ab. Prüfe die Auswirkungen einzeln: Sie sind keine Fehler und werden nicht mit Alle beheben angewendet.",
    proRecommendations: "Empfehlungen für Pro",
    proRecommendationsBody:
      "Diese Einstellungen entsprechen den Hardware-Empfehlungen, erfordern aber Pro. Melde dich an, wenn du bereits ein Abonnement hast.",
    review: "Bitte prüfen",
    empty: "Keine unterstützten Änderungen anzuwenden.",
    emptyBody:
      "Dieses Konto kann keine noch inaktive Hardware-Empfehlung automatisch anwenden. Prüfe die separat aufgeführten Ergebnisse und Optionen.",
    ready: "Ein klarer Bericht. Du entscheidest.",
    readyBody:
      "Die Prüfung ändert keine Einstellungen, löscht keine Dateien und installiert keine Treiber. Unterstützte Korrekturen und manuelle Prüfungen werden getrennt angezeigt.",
    selected: "ausgewählt",
    apply: "Auswahl anwenden",
    confirm: "Änderungen prüfen",
    confirmBody:
      "Nur ausgewählte Einstellungen werden geändert. Dateien, Autostart-Programme, Treiber und Schutzfunktionen bleiben unverändert. Unterstützte Einstellungen lassen sich im Änderungsverlauf wiederherstellen.",
    cancel: "Abbrechen",
    verified: "Anwendung bestätigt",
    failed: "Nicht angewendet oder nicht bestätigt",
    skipped: "Nicht mehr geeignet",
    retry: "Vor einem neuen Versuch erneut prüfen.",
    verifying: "Wird angewendet und überprüft…",
    admin: "Administratorfreigabe",
    noReview: "Keine weiteren Hinweise aus den abgeschlossenen Prüfungen.",
    unavailable: "Nicht verfügbare Prüfungen bleiben unbekannt, nicht bestanden.",
    manual: "Prüfen",
    probes: [
      "Windows-Einstellungen",
      "Unterstützte Änderungen",
      "Hardware-Empfehlungen",
      "Systemprofil",
      "Freier Speicherplatz",
      "Autostart-Programme",
      "Speichernutzung",
      "Ausstehender Neustart",
      "Schutzfunktionen",
      "Treiberdaten",
      "Geplante Autostart-Aufgaben",
      "Optionale Windows-Apps",
      "Hintergrundeffizienz",
    ],
    observations: {
      tasks: [
        "Autostart-Aufgaben prüfen",
        "Diese Drittanbieter-Aufgaben starten bei Anmeldung oder Systemstart. Prüfe ihren Zweck vor dem Deaktivieren.",
      ],
      apps: [
        "Optionale Windows-Apps prüfen",
        "Diese Apps sind für dieses Konto installiert und entfernbar. Behalte benötigte Apps; lokale Daten können verloren gehen.",
      ],
      efficiency: [
        "Hintergrundregeln können nicht wirken",
        "Die globale Energiebegrenzung ist deaktiviert. Prüfe die widersprüchliche Einstellung unter Leistung vor der Verwendung der Regeln.",
      ],
      storage: [
        "Wenig freier Speicherplatz",
        "Weniger als 15 % sind frei. Prüfe Dateien und Bereinigungsoptionen vor dem Löschen. Die Werte zeigen freien Speicherplatz.",
      ],
      startup: [
        "Autostart-Programme prüfen",
        "Diese Einträge sind aktiviert. Behalte benötigte Programme; ihre Anwesenheit allein beweist keinen langsamen Start.",
      ],
      memory: [
        "Hohe Speichernutzung während der Prüfung",
        "Prüfe zuerst die laufenden Apps. Ein einzelner Wert beweist kein Problem; Bereinigung kann Apps vorübergehend verlangsamen.",
      ],
      restart: [
        "Windows meldet einen ausstehenden Neustart",
        "Speichere deine Arbeit und starte bei Gelegenheit neu. PC Tweaker startet den PC nicht selbst neu.",
      ],
      security: [
        "Ein Windows-Schutz scheint deaktiviert",
        "Prüfe Windows-Sicherheit oder UAC. Verwaltete Geräte und andere Antivirenprogramme können eine andere Konfiguration erfordern.",
      ],
      drivers: [
        "Datum dieses Treibers prüfen",
        "Das gemeldete Datum ist mindestens zwei Jahre alt. Das beweist weder einen veralteten Treiber noch ein verfügbares kompatibles Update.",
      ],
    },
  },
  pt: {
    ...en,
    eyebrow: "VERIFICAÇÃO DO SISTEMA",
    title: "Descubra o que precisa de atenção.",
    intro:
      "Verifique configurações, armazenamento, inicialização, memória, proteções e datas dos drivers antes de fazer alterações.",
    start: "Analisar este PC",
    running: "Lendo o sistema",
    presenting: "A preparar os resultados",
    discovering: "A identificar categorias de dispositivos",
    waitingWindows: "A aguardar o inventário do Windows",
    deviceClasses: "categorias de dispositivos verificadas",
    elapsed: "Tempo decorrido",
    scanning: "A analisar",
    finishing: "A concluir",
    pause: "Pausar",
    resume: "Retomar",
    stop: "Parar",
    finish: "Terminar",
    paused: "Em pausa",
    pausedLine: "Em pausa: {done} de {total} verificações concluídas",
    pausedHint: "Retomar lê apenas o que falta. Fechar o PC Tweaker descarta uma análise em pausa.",
    partialTitle: "Análise parcial",
    partialBody: "{done} de {total} verificações concluídas. Por verificar: {missing}.",
    olderNote: "Alguns destes resultados foram lidos às {time}, antes da pausa.",
    complete: "Análise concluída",
    results: "Resultados da análise",
    hideResults: "Ocultar resultados",
    showResults: "Mostrar resultados",
    partial: "Algumas verificações falharam",
    scope: "O que verificamos",
    newChecks: "3 novas verificações",
    newDetails: [
      "Tarefas de terceiros executadas no início de sessão ou arranque.",
      "Aplicações opcionais instaladas; a remoção é uma escolha sua.",
      "Deteta conflitos que impedem as regras de funcionar.",
    ],
    sources: "verificações concluídas",
    recommendations: "Alterações recomendadas",
    optional: "Melhorias opcionais",
    optionalBody:
      "Estas definições inativas dependem da utilização do PC. Analise os efeitos individualmente: não são erros e não entram em Corrigir tudo.",
    proRecommendations: "Recomendações disponíveis com Pro",
    proRecommendationsBody:
      "Estas definições correspondem às recomendações de hardware, mas exigem Pro. Se já tem uma assinatura, entre na sua conta.",
    review: "Para revisar",
    empty: "Nenhuma alteração compatível para aplicar.",
    emptyBody:
      "Esta conta não pode aplicar automaticamente nenhuma definição recomendada para o hardware que ainda esteja inativa. Analise os resultados e as opções em separado.",
    ready: "Um relatório claro. Você escolhe cada alteração.",
    readyBody:
      "A análise não altera configurações, exclui arquivos nem instala drivers. As correções compatíveis ficam separadas dos itens que precisam da sua decisão.",
    selected: "selecionados",
    apply: "Aplicar seleção",
    confirm: "Revisar alterações",
    confirmBody:
      "Somente as configurações selecionadas serão alteradas. Arquivos, programas de inicialização, drivers e proteções não serão modificados. Restaure configurações compatíveis pelo histórico.",
    cancel: "Cancelar",
    verified: "Aplicação verificada",
    failed: "Não aplicados ou não verificados",
    skipped: "Não mais elegíveis",
    retry: "Analise novamente antes de tentar de novo.",
    verifying: "Aplicando e verificando…",
    admin: "Permissão de administrador",
    noReview: "Nenhum item para revisar nas verificações concluídas.",
    unavailable: "Verificações indisponíveis permanecem desconhecidas, não aprovadas.",
    manual: "Revisar",
    probes: [
      "Configurações do Windows",
      "Alterações compatíveis",
      "Recomendações de hardware",
      "Perfil do sistema",
      "Espaço livre",
      "Programas de inicialização",
      "Uso de memória",
      "Reinício pendente",
      "Proteções",
      "Datas dos drivers",
      "Tarefas de arranque agendadas",
      "Aplicações opcionais do Windows",
      "Eficiência em segundo plano",
    ],
    observations: {
      tasks: [
        "Rever tarefas de arranque",
        "Estas tarefas de terceiros estão ativas no início de sessão ou arranque. Reveja a sua finalidade antes de as desativar.",
      ],
      apps: [
        "Rever aplicações opcionais",
        "Estas aplicações estão instaladas e podem ser removidas nesta conta. Mantenha as que utiliza; a remoção pode apagar dados locais.",
      ],
      efficiency: [
        "As regras não podem atuar",
        "A limitação energética global está desativada. Reveja a definição em conflito em Desempenho antes de utilizar as regras.",
      ],
      storage: [
        "Pouco espaço livre",
        "Menos de 15 % está livre. Revise arquivos e opções de limpeza antes de excluir. Os valores indicam espaço livre.",
      ],
      startup: [
        "Revise os programas de inicialização",
        "Estes programas estão habilitados. Mantenha os que utiliza; sua presença não comprova uma inicialização lenta.",
      ],
      memory: [
        "Uso elevado de memória durante a análise",
        "Revise primeiro os aplicativos abertos. Uma única leitura não comprova um problema; a limpeza pode deixar apps temporariamente mais lentos.",
      ],
      restart: [
        "O Windows indica um reinício pendente",
        "Salve seu trabalho e reinicie quando for conveniente. O PC Tweaker não reiniciará o computador.",
      ],
      security: [
        "Uma proteção do Windows parece desativada",
        "Verifique Segurança do Windows ou UAC. Dispositivos gerenciados e antivírus de terceiros podem precisar de outra configuração.",
      ],
      drivers: [
        "Revise a data deste driver",
        "A data informada tem pelo menos dois anos. Isso não comprova que o driver esteja desatualizado ou exista uma atualização compatível.",
      ],
    },
  },
};
